-- 
-- Please see the license.html file included with this distribution for 
-- attribution and copyright information.
--

function registerDefaultSets()
	for k,v in pairs(ImageDeathMarkerData.getDefaultSets()) do
		ImageDeathMarkerManager.registerDefaultSet(k, v);
	end
	ImageDeathMarkerManager.setCreatureTypeDefault("", "blood_red");
end

local _tDefaultSets = {
	["blood_black"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FF202020",
	},
	["blood_blue"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FF3040C0",
	},
	["blood_brown"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FF705030",
	},
	["blood_green"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FF008000",
	},
	["blood_red"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FF800000",
	},
	["blood_violet"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FF8000C0",
	},
	["blood_yellow"] = {
		"images/Death Markers/blood/blood_01.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_02.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_03.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_04.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_05.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_06.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_07.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_08.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_09.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_10.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_11.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_12.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_13.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_14.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_15.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_16.png@SmiteWorks Assets",
		"images/Death Markers/blood/blood_17.png@SmiteWorks Assets",
		["tint"] = "FFB0A000",
	},
	["skull"] = {
		"images/Death Markers/skull/skull_01.png@SmiteWorks Assets",
		"images/Death Markers/skull/skull_02.png@SmiteWorks Assets",
	},
	["skull_round"] = {
		"images/Death Markers/skull/skull_round_01.png@SmiteWorks Assets",
		"images/Death Markers/skull/skull_round_02.png@SmiteWorks Assets",
	},
	["skull_square"] = {
		"images/Death Markers/skull/skull_square_01.png@SmiteWorks Assets",
		"images/Death Markers/skull/skull_square_02.png@SmiteWorks Assets",
	},
	["tombstone"] = {
		"images/Death Markers/tombstone/tombstone_01.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_02.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_03.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_04.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_05.png@SmiteWorks Assets",
	},
	["tombstone_round"] = {
		"images/Death Markers/tombstone/tombstone_round_01.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_round_02.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_round_03.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_round_04.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_round_05.png@SmiteWorks Assets",
	},
	["tombstone_square"] = {
		"images/Death Markers/tombstone/tombstone_square_01.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_square_02.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_square_03.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_square_04.png@SmiteWorks Assets",
		"images/Death Markers/tombstone/tombstone_square_05.png@SmiteWorks Assets",
	},
};
function getDefaultSets()
	return _tDefaultSets;
end
function addDefaultSet(sKey, tSet)
	if not sKey or not tSet or (type(tSet) ~= "table") or (#tSet == 0) then
		return;
	end
	_tDefaultSets[sKey] = tSet;
end
